### ISSUE TITLE
The issue with fullmosaic.py

### ISSUE THREAD

**Issue by liweihung** [liweihung/nightskies#9]
The fullmosaic.py script crushes on line 176 around `skytopomags.save(gridsetp+'skytopomags')` for Davyd and Damon. However, the same script runs smoothly for others. This problem seems to related to the math done on the previous line: `skytopomags = zeropoint[int(s[0])-1] + psa - 2.5*arcpy.sa.Log10(arcpy.sa.Raster(gridsetp+'skytopo')/exptime[0])`

@dbetchkal or @damonjoycenps , can you post the error message you get when the script crashes?

My new hypothesis is that the array skytopomags is too large to handle by some arcpy functions. I suggest one compare the fullmosaic.py to medianmosaic.py. In fullmosaic.py, the images are in full resolution, where as in medianmosaic.py, the images are sub-sampled before calling the `save` function.  Among the four mosaic scripts (galactic.py, zodiacal.py, medianmosaic.py, and fullmosaic.py), the first three are sub-sampled where as the last one is not, and this is what leads me to think this bug might be related to the memory issue.

**Comment by dbetchkal** [comment]
@liweihung , here's the error message I get when running from the command line (or using `ipython`) and ArcMap version 10.5.0.6481:

`Traceback (most recent call last):`
`   File "C:\...\multiprocessing\process.py", line 267, in _bootstrap self.run()`
`   File "C:\...\multiprocessing\process.py", line 114 in run self._target(*self._args, **self._kwargs)`
`   File "C:\...\nightskies\process.py", line 204, in mosaic_full`
`      fullmosaic.mosaic(args[0], args[1], filter)`
`   File "C:\...\nightskies\fullmosaic.py", line 172, in mosaic`
`      print "Converting the mosaic to mag per squard arcsec"`
`   File "C:\...\nightskies\fullmosaic.py", line 172, in mosaic`
`      print "Converting the mosaic to mag per squard arcsec"`
`   File "C:\Users\...\envs\NightSkies\bdb.py", line 49, in trace_dispatch`
`      return self.dispatch_line(frame)`
`   File C:\Users\...\envs\NightSkies\bdb.py", line 68, in dispatch_line`
`      if self.quitting: raise BdbQuit`

**Comment by Sharolyn** [comment]
Hi Li Wei,Good idea and total plausible in arcpy.   I think that breaking down the math into sections might help.  Maybe:
stm1 = arcpy.sa.raster(gridsetp + skytopo)stm2 = arcpy.sa.log10(stm1)stm3 = 2.5 * stm2 / esptime[0]
skytopomags = zeropoint[int(s[0])-1] + psa - stm3
See if that works.   I believe that Raster Calculator creates temp rasters for each stage of the calculations thus calling each stage separately might save memory.
Let me know if this works or where it crashes.  Or ignore my comment :)
Cheers,
Sharolyn
    On Tuesday, July 17, 2018, 10:46:31 AM MDT, Li-Wei Hung <notifications@github.com> wrote:  
 
 
The fullmosaic.py script crushes on line 176 around skytopomags.save(gridsetp+'skytopomags') for Davyd and Damon. However, the same script runs smoothly for others. This problem seems to related to the math done on the previous line: skytopomags = zeropoint[int(s[0])-1] + psa - 2.5*arcpy.sa.Log10(arcpy.sa.Raster(gridsetp+'skytopo')/exptime[0])

@dbetchkal or @damonjoycenps , can you post the error message you get when the script crashes?

My new hypothesis is that the array skytopomags is too large to handle by some arcpy functions. I suggest one compare the fullmosaic.py to medianmosaic.py. In fullmosaic.py, the images are in full resolution, where as in medianmosaic.py, the images are sub-sampled before calling the save function. Among the four mosaic scripts (galactic.py, zodiacal.py, medianmosaic.py, and fullmosaic.py), the first three are sub-sampled where as the last one is not, and this is what leads me to think this bug might be related to the memory issue.

**Comment by dbetchkal** [comment]
@liweihung , @Sharolyn , @damonjoycenps 

Took about a day of testing, but eventually found (and have pushed) a bug fix.   Breaking the calculation into steps seems to have helped, but there were a few other snags with pathnames when saving raster files.  Use of `os.sep` seems to have cleared those up nicely.  

I would like to ask someone who previously *wasn't* having issues to try to run the pipeline again just to check that I haven't introduced any issues for other users.  Thank you!

**Comment by liweihung** [comment]
It runs fine in my computer. However, the scale of the final image is wrong. I noticed that the revised math is off. The exposure time should be inside of the log function (see the original equation). David, once you fixed the math, try it again on your computer and if it runs smoothly, push it and I'll try on my end. Looks promising!
